### ISSUE TITLE
In groups, add a button to select another random person (design)

### ISSUE THREAD

**Issue by fdaciuk** [codeinthedarkbrasil/manage-citd#19]

**Comment by murimessias** [comment]
As previously noted in #26, I'm happy to take this on! I pre-designed the workflow to keep it consistent while I was working on #26. 🖖🏾

**Comment by fdaciuk** [comment]
All yours @murimessias ❤️

**Comment by murimessias** [comment]
I've created a [Figma Prototype](https://www.figma.com/proto/Hl2ZWDVm0clMEADSi2mvaM/Code-in-The-Dark---Back-Office-%7C-Actions?page-id=0%3A1&type=design&node-id=1-594&viewport=391%2C140%2C0.74&t=l56qWExMb9lbcA7k-1&scaling=min-zoom&starting-point-node-id=1%3A2292&mode=design) with that flow. The main ideia is the same as created in #26. Also, I'm providing screenshots here too 🤘🏾

Select User
<img width="1442" alt="image" src="https://github.com/codeinthedarkbrasil/manage-citd/assets/58787878/d54a8cfb-0d8c-46eb-a6ce-af403125e75a">

Confirm Sort
<img width="1442" alt="image" src="https://github.com/codeinthedarkbrasil/manage-citd/assets/58787878/135547de-59a2-466d-8db0-26dce26cb24e">

Display New User
<img width="1442" alt="image" src="https://github.com/codeinthedarkbrasil/manage-citd/assets/58787878/0b59ccc6-4ac3-43a3-8eb1-0b676d49d0e2">

**Comment by fdaciuk** [comment]
Looks good to me! @vmarcosp what do you think?

**Comment by fdaciuk** [comment]
Ok @vmarcosp have approved! The only thing he's asking is: are you using lucid icons?

**Comment by murimessias** [comment]
I got the icons that were in the original layout of Figma. If it's not from Lucide Icons, I can change it as well.

**Comment by fdaciuk** [comment]
Perfect! In that case, we are good to go :D

**Comment by murimessias** [comment]
[Final Design](https://www.figma.com/file/Hl2ZWDVm0clMEADSi2mvaM/Code-in-The-Dark---Back-Office-%7C-Actions?type=design&node-id=0-1&mode=design)

**Comment by fdaciuk** [comment]
Great job @murimessias! Thanks a lot ❤️✨💃🏾
