### ISSUE TITLE
In groups, add a button to select a winner (design)

### ISSUE THREAD

**Issue by fdaciuk** [codeinthedarkbrasil/manage-citd#26]

**Comment by murimessias** [comment]
I can do it! 🖌️

**Comment by fdaciuk** [comment]
Hey @murimessias! This issue depends on #30, probably I should fix the #30 before the #19 xD

**Comment by murimessias** [comment]
This issue and #19 are about the design layout, isn't it? If it's needed, I can help work with Figma 👨🏾‍🎨

**Comment by fdaciuk** [comment]
Ah, ok! I'll assign this issue to you, and create a new one to implementation. All yours ❤️

**Comment by murimessias** [comment]
I've created a [Figma Prototype](https://www.figma.com/proto/Hl2ZWDVm0clMEADSi2mvaM/Code-in-The-Dark---Back-Office-%7C-Actions?page-id=1%3A2802&type=design&node-id=1-2803&viewport=567%2C479%2C0.18&t=gvCNcCRL1DZDI5ib-1&scaling=min-zoom&starting-point-node-id=1%3A2803&mode=design) with that flow. The main ideia is to use a tooltip to display action name. Additionally, I'm providing screenshots here 🫰🏾 

Select Winner (sneak peek of sorting a participant #19 👀)
<img width="1260" alt="image" src="https://github.com/codeinthedarkbrasil/manage-citd/assets/58787878/211cdbef-43b8-41d5-9561-040cde34210d">

Confirm Winner
<img width="1260" alt="image" src="https://github.com/codeinthedarkbrasil/manage-citd/assets/58787878/c9001b56-8037-498d-a4a6-23873b182f31">

Display Winner
<img width="1260" alt="image" src="https://github.com/codeinthedarkbrasil/manage-citd/assets/58787878/8b7ebeaa-56a3-4373-b5de-f72e23e449f6">

**Comment by fdaciuk** [comment]
Nice @murimessias! In the winner screen, I guess we could just show the person in the "Final" list (shown as "Semifinal" in layout), instead of removing the othe participants. Maybe we could show the others in grayscale, what do you think?

@vmarcosp your opinion here would be great! :D

**Comment by murimessias** [comment]
Yeah, I was thinking of doing it that way. I'd change! It's not fair for previous participants to have their participation removed. 🤦🏾‍♂️

**Comment by murimessias** [comment]
@fdaciuk I updated the layout and used a green overlay with opacity. This helps differentiate between users who use grayscale in their profile pictures.

Display Winner
<img width="1489" alt="image" src="https://github.com/codeinthedarkbrasil/manage-citd/assets/58787878/d0afabd2-d294-41b6-a017-7f9910f102d5">

**Comment by fdaciuk** [comment]
Looks nice! Let's see what @vmarcosp thinks about this :D

**Comment by murimessias** [comment]
[Final Design](https://www.figma.com/file/Hl2ZWDVm0clMEADSi2mvaM/Code-in-The-Dark---Back-Office-%7C-Actions?type=design&node-id=1-2802&mode=design)

**Comment by fdaciuk** [comment]
Good job @murimessias! Thanks a lot ❤️ ✨ 💃🏾
